#!/usr/bin/env bash
# displays information about subdomains

print_info() {
	domain="$1"
	subdomain="$2"
	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | sed '1d' | awk -v res="$subdomain" '{printf "The subdomain %s is a %s record and points to %s\n", res, $4, $5}'
}

for subdomain in "www" "lb-01" "web-01" "web-02"
do
    if [ -z "$2" ] || [ "$2" == "$subdomain" ] ;
    then
        print_info "$1" "$subdomain"
    fi
done
