#!/usr/bin/env bash
# a script used to configure a Nginx server
sudo apt-get update
sudo apt-get -y install nginx
echo "Hello world" > /var/www/html/index.html
sed -i 'server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4? permanent; }' /etc/nginx/sites-available/default
service nginx restart
