#!/usr/bin/env bash
# a script used to configure a Nginx server

sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html

echo "Hello Wolrd!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
