#!/usr/bin/env bash
# configure Nginx so that its HTTP response contains a custom headers

apt-get update
apt-get -y install nginx

mkdir -p /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404_error.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404_error.html

echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root /etc/nginx/html;
    index index.html index.htm;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404_error.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
