#!/usr/bin/env bash
# configuring a load balancing server

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
	"
frontend localnodes
	bind *:80
	mode http
	default_backend nodes
backend nodes
	mode http
	balance roundrobin
	server 327919-web-01 100.26.169.125
	server 327919-web-02 52.207.134.230" >> /etc/haproxy/haproxy.cfg

sudo service haproxy restart
