#!/usr/bin/env bash
# displaying time for 12 hours and 59 minutes
i=0
j=1
while [ $i -le 12 ]; do
    j=1
    echo "Hour: $i"
    while [ $j -lt 60 ]; do
        echo "$j"
        ((j++))
    done
    ((i++))
done
