#!/usr/bin/env bash
# a script that configures the container to run nginx as nginx user

sed -i '1i\user nginx;' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
service nginx restart
